name: vSolar
favicon: null
layout_spectrum: 0
typography_spectrum: 0.35017
title: vSolar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2825'
    - '#bcbaae'
    - '#79665f'
    - '#c09560'
    - '#ffa33c'
  brandStrength: 1
  lightness: 0.3403867641463876
  saturation: 0.23301790351979434
  rhythmicContrast: 0.3895791282411665
purpose: []
