name: vSolar
favicon: null
layout_spectrum: 0.7318
typography_spectrum: 0.35017
title: vSolar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2825'
    - '#bcbaae'
    - '#79665f'
    - '#c09560'
    - '#ffa33c'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.3895791282411665
purpose: []
